create extension if not exists vector;

create table users (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    email varchar(255) unique,
    fullname varchar(255),
    image_url varchar(255),
    password varchar(255),
    provider varchar(255),
    role varchar(255),
    username varchar(255) unique,
    primary key (id)
);

create table user_settings (
    id bigint generated by default as identity,
    user_id bigint not null unique,
    api_key_encrypted TEXT,
    app_theme varchar(255) not null,
    primary key (id)
);

create table recipes (
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    steps TEXT,
    title varchar(255) not null,
    primary key (id)
);

create table favorite_recipe (
    recipe_id bigint not null,
    user_id bigint not null,
    primary key (recipe_id, user_id)
);

create table ingredients (
    id bigint generated by default as identity,
    recipe_id bigint,
    name TEXT,
    primary key (id)
);

create table recipe_embedding (
    created_at timestamp(6),
    id bigint generated by default as identity,
    recipe_id bigint,
    embedding vector(1536),
    primary key (id)
);

create table conversations (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    user_id bigint not null,
    title TEXT,
    primary key (id)
);

create table messages (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    conversation_id bigint not null,
    content TEXT,
    role varchar(255) not null,
    primary key (id)
);

alter table user_settings add constraint fk_user_settings_user foreign key (user_id) references users;
alter table favorite_recipe add constraint fk_favorite_recipe_recipe foreign key (recipe_id) references recipes;
alter table favorite_recipe add constraint fk_favorite_recipe_user foreign key (user_id) references users;
alter table ingredients add constraint fk_ingredients_recipe foreign key (recipe_id) references recipes;
alter table conversations add constraint fk_conversations_user foreign key (user_id) references users;
alter table messages add constraint fk_messages_conversation foreign key (conversation_id) references conversations;