create table conversation_contexts (
    id bigint generated by default as identity,
    conversation_id bigint not null,
    list_type varchar(255) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

alter table conversation_contexts
    add constraint fk_conversation_contexts_conversation foreign key (conversation_id) references conversations;

alter table conversation_contexts
    add constraint uq_conversation_contexts_conversation_list_type unique (conversation_id, list_type);

create table conversation_context_recipe_ids (
    conversation_context_id bigint not null,
    list_position integer not null,
    recipe_id bigint not null,
    primary key (conversation_context_id, list_position)
);

alter table conversation_context_recipe_ids
    add constraint fk_conversation_context_recipe_ids_context foreign key (conversation_context_id) references conversation_contexts;
